#ifndef IZENELIB_VERSION_H
#define IZENELIB_VERSION_H

#define IZENELIB_VERSION_MAJOR @CPACK_PACKAGE_VERSION_MAJOR@
#define IZENELIB_VERSION_MINOR @CPACK_PACKAGE_VERSION_MINOR@
#define IZENELIB_VERSION_PATCH @CPACK_PACKAGE_VERSION_PATCH@

#define IZENELIB_VERSION "@CPACK_PACKAGE_VERSION_MAJOR@.@CPACK_PACKAGE_VERSION_MINOR@.@CPACK_PACKAGE_VERSION_PATCH@"

#endif