#ifndef _EN_ALPHABET_H_
#define _EN_ALPHABET_H_

/* Alphabet table for en language, generated by izenelib::am::trie::AlphabetGenerator */

static const unsigned int en_size = 26;

static char en[26] =
{
	97,	98,	99,	100,	101,	102,	103,
104,	105,	106,	107,	108,	109,	110,	111,
112,	113,	114,	115,	116,	117,	118,	119,
120,	121,	122};

#endif
