#include <am/trie/alphabet_en.hpp>

NS_IZENELIB_AM_BEGIN


/* Alphabet table for en language, generated by izenelib::am::trie::AlphabetGenerator */

char en[en_size] =
{
	97,	98,	99,	100,	101,	102,	103,
104,	105,	106,	107,	108,	109,	110,	111,
112,	113,	114,	115,	116,	117,	118,	119,
120,	121,	122};


NS_IZENELIB_AM_END
