/**
 * @file izenelib/driver/Keys.inl
 * @date Created <2011-01-25 15:35:16>
 *
 * This file is generated by generators/driver_keys.rb by collecting keys
 * from source code. Do not edit this file directly.
 */

#define SF1_DRIVER_KEYS \
(DOCID)\
(_categories)\
(_duplicated_document_count)\
(_id)\
(_image_id)\
(_rank)\
(_similar_document_count)\
(acl_tokens)\
(action)\
(analyzer)\
(analyzer_result)\
(apply_la)\
(category_id)\
(check_time)\
(cid)\
(cname)\
(collection)\
(collections)\
(conditions)\
(content)\
(controller)\
(counter)\
(default_ranking_model)\
(doccount)\
(docid)\
(docid_list)\
(document_count)\
(document_support_count)\
(duplicate_with)\
(duration)\
(elapsed_time)\
(errors)\
(filter)\
(from)\
(general_classifier_language)\
(group)\
(group_count)\
(header)\
(highlight)\
(hit_docs_num)\
(id)\
(in)\
(index)\
(indices)\
(keywords)\
(label)\
(labels)\
(last_modified)\
(left_time)\
(level)\
(limit)\
(log_keywords)\
(manmade)\
(message)\
(meta)\
(mining)\
(mining_result)\
(name)\
(name_entity)\
(name_entity_item)\
(name_entity_list)\
(name_entity_type)\
(offset)\
(operator_)\
(order)\
(page_count)\
(page_start)\
(popular)\
(popular_queries)\
(prefix)\
(process_time)\
(progress)\
(property)\
(query)\
(ranking_model)\
(realtime)\
(realtime_queries)\
(recent)\
(refined_query)\
(related_queries)\
(remote_ip)\
(remove_duplicated_result)\
(resource)\
(resources)\
(schema)\
(search)\
(search_session)\
(seconds)\
(select)\
(session_id)\
(similar_to)\
(similar_to_image)\
(snippet)\
(sort)\
(source)\
(status)\
(sub_labels)\
(success)\
(summary)\
(summary_property_alias)\
(summary_sentence_count)\
(system_events)\
(taxonomy)\
(taxonomy_label)\
(timers)\
(timestamp)\
(to)\
(tokenizer_list)\
(top_k_count)\
(total_count)\
(total_server_time)\
(type)\
(use_original_keyword)\
(use_synonym_extension)\
(user_queries)\
(value)\
(warnings)\
(wildcard_type)


/* LOCATIONS

DOCID
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:261
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:263
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:316
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:341
  process/new-trinity/ba-process/controllers/DocumentsController.cpp:440

_categories
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:127

_duplicated_document_count
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:108

_id
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:33
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:77
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:256
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:258
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:316
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:333
  process/new-trinity/ba-process/controllers/FacetedController.cpp:401

_image_id
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:121
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:183

_rank
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:78

_similar_document_count
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:115

acl_tokens
  core/driver/Request.cpp:49

action
  core/driver/Request.cpp:44

analyzer
  process/new-trinity/ba-process/parsers/SearchParser.cpp:169
  process/new-trinity/ba-process/controllers/SchemaController.cpp:150

analyzer_result
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:392
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:410

apply_la
  process/new-trinity/ba-process/parsers/SearchParser.cpp:170

category_id
  process/new-trinity/ba-process/controllers/FacetedController.cpp:433
  process/new-trinity/ba-process/controllers/FacetedController.cpp:435

check_time
  process/new-trinity/ba-process/DriverConnection.cpp:174
  process/new-trinity/ba-process/DriverConnection.cpp:212

cid
  process/new-trinity/ba-process/controllers/FacetedController.cpp:403

cname
  process/new-trinity/ba-process/controllers/FacetedController.cpp:404

collection
  process/new-trinity/ba-process/controllers/KeywordsController.cpp:64
  process/new-trinity/ba-process/controllers/QueryCorrectionController.cpp:17
  process/new-trinity/ba-process/controllers/SchemaController.cpp:100
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:34
  process/new-trinity/ba-process/controllers/DocumentsController.cpp:451
  process/new-trinity/ba-process/controllers/CommandsController.cpp:18
  process/new-trinity/ba-process/controllers/FacetedController.cpp:421
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:64
  process/new-trinity/ba-process/controllers/StatusController.cpp:43
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:177
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:233

collections
  process/new-trinity/ba-process/controllers/SchemaController.cpp:61

conditions
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:304
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:297
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:58
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:59

content
  process/new-trinity/ba-process/controllers/FacetedController.cpp:45
  process/new-trinity/ba-process/controllers/FacetedController.cpp:101
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:139

controller
  core/driver/Request.cpp:43

counter
  process/new-trinity/ba-process/controllers/StatusController.cpp:69

default_ranking_model
  process/new-trinity/ba-process/controllers/SchemaController.cpp:121

doccount
  process/new-trinity/ba-process/controllers/FacetedController.cpp:160
  process/new-trinity/ba-process/controllers/FacetedController.cpp:281

docid
  process/new-trinity/ba-process/controllers/FacetedController.cpp:402

docid_list
  process/new-trinity/ba-process/controllers/FacetedController.cpp:448

document_count
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:207
  process/new-trinity/ba-process/controllers/CommandsController.cpp:57
  process/new-trinity/ba-process/controllers/CommandsController.cpp:100
  process/new-trinity/ba-process/controllers/StatusController.cpp:54
  process/new-trinity/ba-process/controllers/StatusController.cpp:67

document_support_count
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:239

duplicate_with
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:92

duration
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:182
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:253
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:257
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:265

elapsed_time
  process/new-trinity/ba-process/controllers/StatusController.cpp:63

errors
  core/include/izenelib/driver/Response.h:37

filter
  process/new-trinity/ba-process/controllers/SchemaController.cpp:151

from
  process/new-trinity/ba-process/parsers/GroupingParser.cpp:110
  process/new-trinity/ba-process/parsers/GroupingParser.cpp:122

general_classifier_language
  process/new-trinity/ba-process/controllers/SchemaController.cpp:123

group
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:309

group_count
  process/new-trinity/ba-process/parsers/GroupingParser.cpp:107

header
  core/include/izenelib/driver/Request.h:86
  core/include/izenelib/driver/Response.h:80

highlight
  process/new-trinity/ba-process/parsers/SelectParser.cpp:109

hit_docs_num
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:178
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:244

id
  process/new-trinity/ba-process/controllers/FacetedController.cpp:159
  process/new-trinity/ba-process/controllers/FacetedController.cpp:280

in
  process/new-trinity/ba-process/parsers/SearchParser.cpp:118

index
  process/new-trinity/ba-process/controllers/StatusController.cpp:51

indices
  process/new-trinity/ba-process/controllers/SchemaController.cpp:128

keywords
  process/new-trinity/ba-process/parsers/SearchParser.cpp:89
  process/new-trinity/ba-process/controllers/QueryCorrectionController.cpp:18
  process/new-trinity/ba-process/controllers/AutoFillController.cpp:91

label
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:206

labels
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:196

last_modified
  process/new-trinity/ba-process/controllers/StatusController.cpp:53
  process/new-trinity/ba-process/controllers/StatusController.cpp:68
  process/new-trinity/ba-process/controllers/StatusController.cpp:75
  process/new-trinity/ba-process/controllers/StatusController.cpp:82

left_time
  process/new-trinity/ba-process/controllers/StatusController.cpp:64

level
  process/new-trinity/ba-process/controllers/FacetedController.cpp:157
  process/new-trinity/ba-process/controllers/FacetedController.cpp:278
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:137

limit
  core/driver/parsers/PageInfoParser.cpp:21
  core/driver/parsers/PageInfoParser.cpp:23
  process/new-trinity/ba-process/controllers/KeywordsController.cpp:65
  process/new-trinity/ba-process/controllers/DocumentsController.cpp:463
  process/new-trinity/ba-process/controllers/DocumentsController.cpp:465
  process/new-trinity/ba-process/controllers/AutoFillController.cpp:66

log_keywords
  process/new-trinity/ba-process/parsers/SearchParser.cpp:115

manmade
  process/new-trinity/ba-process/controllers/FacetedController.cpp:395

message
  process/new-trinity/ba-process/controllers/TestController.cpp:27
  process/new-trinity/ba-process/controllers/TestController.cpp:27

meta
  process/new-trinity/ba-process/controllers/StatusController.cpp:65

mining
  process/new-trinity/ba-process/controllers/StatusController.cpp:73

mining_result
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:391

name
  process/new-trinity/ba-process/controllers/SchemaController.cpp:120
  process/new-trinity/ba-process/controllers/SchemaController.cpp:148
  process/new-trinity/ba-process/controllers/FacetedController.cpp:158
  process/new-trinity/ba-process/controllers/FacetedController.cpp:279

name_entity
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:607

name_entity_item
  process/new-trinity/ba-process/parsers/SearchParser.cpp:97
  process/new-trinity/ba-process/parsers/SearchParser.cpp:105
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:238

name_entity_list
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:230

name_entity_type
  process/new-trinity/ba-process/parsers/SearchParser.cpp:98
  process/new-trinity/ba-process/parsers/SearchParser.cpp:106

offset
  core/driver/parsers/PageInfoParser.cpp:16
  core/driver/parsers/PageInfoParser.cpp:18

operator_
  core/driver/parsers/ConditionParser.cpp:67

order
  core/driver/parsers/OrderParser.cpp:24

page_count
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:180
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:246

page_start
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:179
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:245

popular
  process/new-trinity/ba-process/controllers/KeywordsController.cpp:126
  process/new-trinity/ba-process/controllers/KeywordsController.cpp:136
  process/new-trinity/ba-process/controllers/KeywordsController.cpp:138

popular_queries
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:592

prefix
  process/new-trinity/ba-process/controllers/AutoFillController.cpp:65

process_time
  process/new-trinity/ba-process/DriverConnection.cpp:176

progress
  process/new-trinity/ba-process/controllers/StatusController.cpp:62

property
  core/driver/parsers/OrderParser.cpp:23
  core/driver/parsers/ConditionParser.cpp:42
  process/new-trinity/ba-process/parsers/GroupingParser.cpp:90
  process/new-trinity/ba-process/parsers/SelectParser.cpp:108
  process/new-trinity/ba-process/parsers/SearchParser.cpp:131
  process/new-trinity/ba-process/controllers/SchemaController.cpp:138
  process/new-trinity/ba-process/controllers/SchemaController.cpp:149

query
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:176
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:232

ranking_model
  process/new-trinity/ba-process/parsers/SearchParser.cpp:176
  process/new-trinity/ba-process/parsers/SearchParser.cpp:178

realtime
  process/new-trinity/ba-process/controllers/KeywordsController.cpp:127
  process/new-trinity/ba-process/controllers/KeywordsController.cpp:163
  process/new-trinity/ba-process/controllers/KeywordsController.cpp:165

realtime_queries
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:597

recent
  process/new-trinity/ba-process/controllers/KeywordsController.cpp:97
  process/new-trinity/ba-process/controllers/KeywordsController.cpp:99

refined_query
  process/new-trinity/ba-process/controllers/QueryCorrectionController.cpp:30
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:620

related_queries
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:587

remote_ip
  process/new-trinity/ba-process/DriverConnection.cpp:162
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:33
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:63

remove_duplicated_result
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:390

resource
  process/new-trinity/ba-process/controllers/DocumentsController.cpp:339
  process/new-trinity/ba-process/controllers/DocumentsController.cpp:384
  process/new-trinity/ba-process/controllers/DocumentsController.cpp:425
  process/new-trinity/ba-process/controllers/DocumentsController.cpp:440

resources
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:42
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:174
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:381
  process/new-trinity/ba-process/controllers/FacetedController.cpp:147
  process/new-trinity/ba-process/controllers/FacetedController.cpp:212
  process/new-trinity/ba-process/controllers/FacetedController.cpp:268
  process/new-trinity/ba-process/controllers/FacetedController.cpp:334
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:564
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:575

schema
  process/new-trinity/ba-process/controllers/SchemaController.cpp:127

search
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:293

search_session
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:215
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:218

seconds
  process/new-trinity/ba-process/controllers/TestController.cpp:42

select
  process/new-trinity/ba-process/controllers/KeywordsController.cpp:75
  process/new-trinity/ba-process/controllers/KeywordsController.cpp:79
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:197
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:289
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:27
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:28

session_id
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:181

similar_to
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:51

similar_to_image
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:133

snippet
  process/new-trinity/ba-process/parsers/SelectParser.cpp:121
  process/new-trinity/ba-process/controllers/SchemaController.cpp:141

sort
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:301
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:44
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:45

source
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:138

status
  process/new-trinity/ba-process/controllers/StatusController.cpp:52
  process/new-trinity/ba-process/controllers/StatusController.cpp:59
  process/new-trinity/ba-process/controllers/StatusController.cpp:74
  process/new-trinity/ba-process/controllers/StatusController.cpp:80

sub_labels
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:212

success
  core/include/izenelib/driver/Response.h:52
  core/include/izenelib/driver/Response.h:60

summary
  process/new-trinity/ba-process/parsers/SelectParser.cpp:110
  process/new-trinity/ba-process/controllers/SchemaController.cpp:140

summary_property_alias
  process/new-trinity/ba-process/parsers/SelectParser.cpp:118

summary_sentence_count
  process/new-trinity/ba-process/parsers/SelectParser.cpp:114

system_events
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:132

taxonomy
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:602

taxonomy_label
  process/new-trinity/ba-process/parsers/SearchParser.cpp:96
  process/new-trinity/ba-process/parsers/SearchParser.cpp:104

timers
  process/new-trinity/ba-process/DriverConnection.cpp:176
  process/new-trinity/ba-process/DriverConnection.cpp:214

timestamp
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:140
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:183
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:274
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:278
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:286

to
  process/new-trinity/ba-process/parsers/GroupingParser.cpp:110
  process/new-trinity/ba-process/parsers/GroupingParser.cpp:125

tokenizer_list
  process/new-trinity/ba-process/controllers/SchemaController.cpp:153

top_k_count
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:89

total_count
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:42
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:83
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:123
  process/new-trinity/ba-process/controllers/DocumentsGetHandler.cpp:188
  process/new-trinity/ba-process/controllers/AutoFillController.cpp:88
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:88
  process/new-trinity/ba-process/controllers/DocumentsSearchHandler.cpp:159

total_server_time
  process/new-trinity/ba-process/DriverConnection.cpp:214

type
  process/new-trinity/ba-process/renderers/DocumentsRenderer.cpp:228
  process/new-trinity/ba-process/controllers/SchemaController.cpp:139

use_original_keyword
  process/new-trinity/ba-process/parsers/SearchParser.cpp:171

use_synonym_extension
  process/new-trinity/ba-process/parsers/SearchParser.cpp:172

user_queries
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:171
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:216
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:221
  process/new-trinity/ba-process/controllers/LogAnalysisController.cpp:224

value
  core/driver/parsers/ConditionParser.cpp:49
  core/driver/parsers/ConditionParser.cpp:56
  core/driver/parsers/ConditionParser.cpp:63

warnings
  core/include/izenelib/driver/Response.h:44

wildcard_type
  process/new-trinity/ba-process/controllers/SchemaController.cpp:122

*/
