///
///  @file : ServiceParameterType.h
///  @date : 8/5/2008
///  @author : TuanQuang Nguyen
///


#if !defined(_SERVICE_PARAMETER_TYPE_)
#define _SERVICE_PARAMETER_TYPE_

namespace messageframework
{
	/**
	 * @brief This enum defines all possible values of parameters of a service
	 */
	enum ServiceParameterType
	{
		FLOAT_TYPE = 0,
		UNSIGNED_INT_TYPE,
		STRING_TYPE,
		USTRING_TYPE,
		GCUSTRING_TYPE,
		VECTOR_OF_FLOAT_TYPE,
		VECTOR_OF_UNSIGNED_INT_TYPE,
        VECTOR_OF_VECTOR_UNSIGNED_INT_TYPE,
		VECTOR_OF_STRING_TYPE,
		LIST_OF_STRING_TYPE,
        VECTOR_OF_USTRING_TYPE,
        VECTOR_OF_GCUSTRING_TYPE,
        ANALYSIS_INFO_TYPE,
        LA_INFORMATION_TYPE,
        LA_INFORMATION_LIST_TYPE,
        VECTOR_OF_COMMON_ITEM_TYPE,
        UNIQUE_DOC_IDENTIFIER_TYPE,
        VECTOR_OF_UNIQUE_DOC_IDENTIFIER_TYPE,
        DOCUMENT_TYPE,
        VECTOR_OF_DOCUMENT_TYPE,
        PROPERTY_VALUE_TYPE,
        VECTOR_OF_PROPERTY_VALUE_TYPE,
        VECTOR_OF_VECTOR_OF_PROPERTY_VALUE_TYPE,
        //VECTOR_OF_DUPLICATE_DOCUMENT_INFO_TYPE,
        BOOL_TYPE,
        VECTOR_OF_CLUSTER_TYPE,
        LA_MANAGER_CONFIG_TYPE,
        DOCUMENT_MANAGER_CONFIG_TYPE,
        STRENGTH_VALUE_LIST_TYPE,
        TERM_FREQUENCY_LIST_TYPE,
        VECTOR_OF_TERM_FREQUENCY_LIST_TYPE,
        OFFSET_INFO_LIST_TYPE,
        VECTOR_OF_OFFSET_INFO_LIST_TYPE,
        DUPLICATE_DOCUMENT_GROUP_LIST_TYPE,
        CBIT_ARRAY_TYPE,
        LOG_DATA_TYPE_TYPE,
        QUERY_LOG_STRUCT_TYPE,
        COLLECTION_QUERY_LOG_STRUCT_TYPE,
        RESULT_DOCID_LIST_STRUCT_TYPE,
        CACHE_USAGE_INFO_STRUCT_TYPE,
        RANKING_MODEL_WEIGHT_STRUCT_TYPE,
        ALGORITHM_WEIGHT_OF_RANKING_MODEL_STRUCT_TYPE,
        LOG_MANAGER_CONFIG_TYPE,
        INDEX_MANAGER_CONFIG_TYPE,
        QUERY_MANAGER_CONFIG_TYPE,
        RANKING_MANAGER_CONFIG_TYPE,
		VECTOR_OF_DOCUMENT_ITEM_TYPE,
		TEXT_QUERY_TYPE,
		INDEXING_PROGRESS_STATUS_TYPE,
        DOCUMENT_FREQUENCY_IN_PROPERTIES_TYPE,
        TEXT_RANKING_TYPE,
        MAP_OF_UNSIGNED_INT_FLOAT_TYPE,
        PROPERTY_TERM_INFO_TYPE,
        VECTOR_OF_PROPERTY_TERM_INFO_TYPE,
        RANKING_SCORE_ITEM_TYPE,
        VECTOR_OF_RANKING_SCORE_ITEM_TYPE,
        VECTOR_OF_QUERY_SCORE_ITEM_TYPE,
        TAXONOMY_REP_TYPE,
		CUSTOM_TYPE,
		UNKNOWN_DATA_TYPE
	};

	/**
	 * @brief This enum defines the way a server serves a service
	 */
	enum PermissionFlag
	{
		SERVE_THROUGH_CONTROLLER = 0,
		SERVE_AT_SERVER,
		UNKNOWN_PERMISSION_FLAG
	};

    /**
     * @brief   This indicates whether a service has a return value or not
     */
    enum ServiceResultFlag
    {
        SERVICE_WITH_RESULT = 0,
        SERVICE_WITHOUT_RESULT
    };

}// end of namespace sf1v5
#endif  // _SERVICE_PARAMETER_TYPE_
