FIND_PATH(WISELIB_INCLUDE_DIR wiselib ~/CodeBase/wiselib/include)

FIND_LIBRARY(WISELIB_LIBRARY wiselib ~/CodeBase/wiselib/lib ) 

IF (WISELIB_INCLUDE_DIR AND WISELIB_LIBRARY)
   SET(WISELIB_FOUND TRUE)
ENDIF (WISELIB_INCLUDE_DIR AND WISELIB_LIBRARY)


IF (WISELIB_FOUND)
      MESSAGE(STATUS "Found wiselib include path: ${WISELIB_INCLUDE_DIR}")
      MESSAGE(STATUS "Found wiselib: ${WISELIB_LIBRARY}")
ELSE (WISELIB_FOUND)
   IF (Wiselib_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find wiselib")
   ENDIF (Wiselib_FIND_REQUIRED)
ENDIF (WISELIB_FOUND)

