#ifndef USTR_TYPES_H
#define USTR_TYPES_H

NS_IZENELIB_UTIL_BEGIN

typedef uint16_t UCS2Char;
enum UCS2CharType { UCS2_NULL = 0, UCS2_UNDEF, UCS2_DIGIT, UCS2_ALPHA, UCS2_KOREAN };

NS_IZENELIB_UTIL_END
#endif // end - USTR_TYPES_H
